### PR TITLE
Add section for how to update the fiscal year

### PR DESCRIPTION
**Pull request by grantg012**

### CODE REVIEW

**Review by hadiahmed098 — CHANGES_REQUESTED** [review]
Can you move this section to below the 'Deploying for production' label? I think it helps maintain a logical flow of information.

**Comment by grantg012** [comment]
I was kinda thinking that someone less knowledgeable with the codebase who's not wanting to setup a whole dev environment might quickly be looking for how to change it (several times it's been pretty last minute / once the school year has started). It's a small enough change it can be done from even github web. And it's not pushing the other sections down that much

**Comment by hadiahmed098** [comment]
That is true, in which case we should probably add how to add an enum value in the database so the `fiscal_year` variable actually has an effect.

**Comment by grantg012** [comment]
Yeah maybe we should just make a different readme?

**Comment by hadiahmed098** [comment]
Yeah that actually might be a better option, split it all up into different files and make a `docs/` folder.

**Comment by grantg012** [comment]
@hadiahmed098 following up on this

**Comment by hadiahmed098** [comment]
Sorry, I got a bit busy - I added a link to the deploy docs in the fiscal year update one. I will update with the new PMA links.

This may be changed with #156 since the SQL commands are getting a bit wild.

**Comment by grantg012** [comment]
I think the SQL backend and source code updates should be switched right? And could you specify, they run the command in a local bash session right?

**Comment by hadiahmed098** [comment]
I believe they are in the right order, the API source code is under the section 'Updating the Code' and the lookup table entry is under the section 'Updating the MySQL Database'.

I can add a line about running these commands in a shell, but that might be unnecessary - Do I also need to include how to access the server's shell?

**Review by hadiahmed098 — APPROVED** [review]

**Comment by hadiahmed098** [comment]
I have swapped the sections, that is a good point

**Comment by grantg012** [comment]
Yep. Pretty unlikely to happen, but if someone isn't aware or takes there sweet time, it would be confusing. Anyway, yeah these changes look great. I think it takes the barrier to entry down low enough for future maintainers with much less experience to keep using 👍

**Pull request merged**
